# Generated by Django 4.2.5 on 2023-09-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Youtube",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=200)),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("video_id", models.CharField(max_length=100)),
                ("thumbnail", models.ImageField(upload_to="youtube/thumbnails")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
