# Generated by Django 4.2.5 on 2023-09-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="youtube",
            name="thumbnail",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
